import {
  ArrowDownLeft,
  ArrowUpDown,
  Battery,
  BookOpen,
  Building,
  Building2,
  Car,
  Club,
  CornerDownLeft,
  Dumbbell,
  FileVideo,
  GalleryHorizontal,
  Headset,
  HelpCircle,
  Home,
  Image,
  Info,
  LandPlot,
  Layers,
  LayoutDashboard,
  Mail,
  MapPin,
  Newspaper,
  Palette,
  Phone,
  Shield,
  Square,
  Trees,
  UserPlus,
  Users,
  Waves,
  X,
} from "lucide-react";
import {
  FaFacebook,
  FaInstagram,
  FaLinkedin,
  FaTwitter,
  FaWhatsapp,
} from "react-icons/fa";

export const Icons = {
  whatsapp: FaWhatsapp,
  phone: Phone,
  mail: Mail,
  map: MapPin,
  facebook: FaFacebook,
  instagram: FaInstagram,
  linkedIn: FaLinkedin,
  twitter: FaTwitter,
  home: Home,
  building: Building,
  buidling2: Building2,
  info: Info,
  headset: Headset,
  layers: Layers,
  dashboard: LayoutDashboard,
  users: Users,
  bookOpen: BookOpen,
  newsPaper: Newspaper,
  help: HelpCircle,
  media: Image,
  fileVideo: FileVideo,
  gallery: GalleryHorizontal,
  userPlus: UserPlus,
  return: CornerDownLeft,
  car: Car,
  shield: Shield,
  battery: Battery,
  square: Square,
  trees: Trees,
  dumbbell: Dumbbell,
  waves: Waves,
  club: Club,
  palette: Palette,
  arrowUpDown: ArrowUpDown,
  landPlot: LandPlot,
  x: X,
};
