import {
  ArrowDownLeft,
  BookOpen,
  Building2,
  CornerDownLeft,
  FileVideo,
  GalleryHorizontal,
  Headset,
  HelpCircle,
  Home,
  Image,
  Info,
  Layers,
  LayoutDashboard,
  Mail,
  MapPin,
  Newspaper,
  Phone,
  UserPlus,
  Users,
} from "lucide-react";
import {
  FaFacebook,
  FaInstagram,
  FaLinkedin,
  FaTwitter,
  FaWhatsapp,
} from "react-icons/fa";

export const Icons = {
  whatsapp: FaWhatsapp,
  phone: Phone,
  mail: Mail,
  map: MapPin,
  facebook: FaFacebook,
  instagram: FaInstagram,
  linkedIn: FaLinkedin,
  twitter: FaTwitter,
  home: Home,
  building: Building2,
  info: Info,
  headset: Headset,
  layers: Layers,
  dashboard: LayoutDashboard,
  users: Users,
  bookOpen: BookOpen,
  newsPaper: Newspaper,
  help: HelpCircle,
  media: Image,
  fileVideo: FileVideo,
  gallery: GalleryHorizontal,
  userPlus: UserPlus,
  return: CornerDownLeft,
};
