export const keywords = [
  // Property Types
  "affordable plots",
  "residential plots for sale",
  "commercial plots for sale",
  "luxury villas for sale",
  "independent houses for sale",
  "apartments for sale",
  "flats for sale",
  "studio apartments for sale",
  "gated community villas",
  "farmhouse for sale",
  "land for sale",
  "open plots for sale",
  "ready to move apartments",
  "row houses for sale",
  "duplex houses for sale",
  "penthouse for sale",

  // Rentals
  "apartments for rent",
  "houses for rent",
  "villas for rent",
  "flats for rent",
  "commercial space for rent",
  "shops for rent",
  "office space for rent",
  "co working space for rent",
  "warehouse for rent",

  // Commercial Real Estate
  "commercial property for sale",
  "office space for sale",
  "retail space for sale",
  "industrial property for sale",
  "showrooms for sale",
  "warehouses for sale",
  "plots for commercial use",

  // Location Based (examples, you can add your city names)
  "affordable plots in Hyderabad",
  "luxury villas in Bangalore",
  "apartments in Mumbai",
  "commercial property in Delhi",
  "plots in Pune",
  "real estate in Chennai",
  "flats in Kolkata",
  "houses in Ahmedabad",

  // Real Estate Investment
  "real estate investment opportunities",
  "best plots for investment",
  "rental income properties",
  "real estate for nri",
  "high return property investment",
  "real estate projects under construction",
  "pre launch real estate projects",

  // General Real Estate Searches
  "buy property online",
  "real estate listings",
  "top real estate projects",
  "affordable housing projects",
  "property for sale near me",
  "houses for sale near me",
  "plots for sale near me",
  "apartments near me",
  "gated community plots",
  "low cost housing projects",
  "luxury real estate",
  "new real estate projects",
  "best builders in India",
  "trusted real estate companies",
];
